"""Histoires originales des dix livres de fêtes (textes et indications d'image)."""

LIVRES = [
    dict(id="noel-etoile", titre="L'étoile de Noël", sousTitre="Une lumière à partager",
         couleur="#c92a2a", age="3 à 6 ans", theme="noel", enfants=("souris", "lapin"),
         resume="Lila cherche l'étoile du sapin. En aidant ses voisins, elle découvre que la plus belle lumière se partage.",
         dedicace="Pour les petites lumières qui brillent ensemble.", pages=[
             ("sapin", "Ce soir, Lila la souris décore le sapin avec Malo le lapin. Il manque quelque chose tout en haut !", "Lila et Malo devant un sapin encore sans étoile."),
             ("etoile", "« Où est notre étoile ? » Lila fouille dans la boîte. Elle ne trouve qu'un vieux ruban doré.", "Lila regarde un ruban doré près du sapin."),
             ("cadeau", "À la fenêtre, leur voisine porte trop de paquets. Lila et Malo courent l'aider.", "Les deux amis aident à porter des cadeaux."),
             ("guirlande", "Puis ils accrochent une guirlande pour Papi Ours, qui ne peut pas atteindre la branche.", "Lila et Malo décorent une branche avec Papi Ours."),
             ("etoile", "Papi plie le ruban doré en forme d'étoile. « Celle-ci raconte tout ce que vous avez fait ! »", "Papi montre une étoile fabriquée avec le ruban."),
             ("sapin", "Lila pose l'étoile au sommet. Devant la maison, tout le monde sourit. Le sapin n'a jamais autant brillé !", "Le sapin illuminé réunit tous les amis."),
         ]),
    dict(id="paques-panier", titre="Le panier de Pâques", sousTitre="Une chasse pleine de surprises",
         couleur="#7b2cbf", age="3 à 6 ans", theme="paques", enfants=("lapin", "souris"),
         resume="Nino veut remplir son panier d'œufs. Quand il en trouve un qui appartient à quelqu'un d'autre, la chasse devient une aventure d'entraide.",
         dedicace="Pour les chasseurs de surprises et de gentillesse.", pages=[
             ("panier", "Nino le lapin part chercher les œufs cachés dans le jardin. Son panier est encore vide.", "Nino tient un panier vide dans un jardin fleuri."),
             ("oeuf", "Sous une tulipe, il trouve un œuf bleu. Derrière un pot, un œuf rose ! Quel bonheur !", "Deux œufs colorés apparaissent parmi les fleurs."),
             ("oeuf", "Mais le troisième œuf porte un petit cœur dessiné. « C'est celui de Mia ! » s'écrie Nino.", "Nino découvre un œuf décoré d'un cœur."),
             ("panier", "Mia la souris a perdu son panier. Ensemble, ils suivent de petites traces dans l'herbe.", "Nino et Mia cherchent un panier dans l'herbe."),
             ("fleur", "Le panier est derrière les jonquilles ! Nino y remet l'œuf de Mia. Elle saute de joie.", "Les amis retrouvent le panier derrière des fleurs."),
             ("panier", "Ils finissent la chasse côte à côte. Deux paniers, des œufs multicolores et une nouvelle amie !", "Nino et Mia montrent leurs paniers remplis d'œufs."),
         ]),
    dict(id="halloween-citrouille", titre="La citrouille d'Halloween", sousTitre="Une soirée sans frayeur",
         couleur="#d9480f", age="3 à 6 ans", theme="halloween", enfants=("chat", "renard"),
         resume="Tao le chat croit que sa citrouille a disparu. Une petite enquête transforme sa peur en fête.",
         dedicace="Pour ceux qui aiment les mystères tout doux.", pages=[
             ("citrouille", "Tao le chat prépare une citrouille pour Halloween. Il lui dessine un grand sourire.", "Tao décore une citrouille souriante."),
             ("masque", "Il part chercher son masque. À son retour, la citrouille a disparu !", "Tao revient avec un masque et découvre une place vide."),
             ("lanterne", "Une lueur orange danse près du portail. Tao se serre contre son amie Zoé.", "Une petite lueur orange brille près du portail."),
             ("brouette", "Derrière le portail, ils trouvent la citrouille… dans la brouette de Papi Renard !", "Tao et Zoé retrouvent la citrouille dans une brouette."),
             ("bonbon", "« Je l'ai mise à l'abri de la pluie », explique Papi. Tao rit : quel drôle de mystère !", "Papi Renard rassure les amis et leur tend des bonbons."),
             ("citrouille", "La citrouille éclaire la porte. Les voisins arrivent, déguisés et souriants. Vive Halloween !", "La citrouille lumineuse accueille les voisins déguisés."),
         ]),
    dict(id="nouvel-an-minuit", titre="Le vœu de minuit", sousTitre="Une nouvelle année commence",
         couleur="#364fc7", age="3 à 6 ans", theme="nouvel-an", enfants=("ours", "lapin"),
         resume="Milo veut rester éveillé jusqu'à minuit. En préparant une fête avec ses amis, il trouve le vœu qu'il veut partager.",
         dedicace="Pour tous les nouveaux départs.", pages=[
             ("horloge", "Milo l'ourson regarde l'horloge. Ce soir, on fête la nouvelle année !", "Milo regarde une grande horloge dans le salon."),
             ("fanion", "Avec Jade, il accroche des fanions. Un bleu, un jaune, un rouge : la pièce devient joyeuse.", "Milo et Jade accrochent des fanions colorés."),
             ("carte", "Chacun dessine un vœu sur une carte. Milo hésite : que souhaiter ?", "Milo réfléchit devant une carte de vœux vierge."),
             ("horloge", "Les aiguilles avancent. Milo bâille. Jade lui apporte un coussin moelleux.", "Milo et Jade attendent près de l'horloge."),
             ("etoile", "Ding ! Minuit ! Dans le ciel, les étoiles brillent. Milo pense à tous ses amis.", "Les amis lèvent les yeux vers un ciel étoilé."),
             ("carte", "Sur sa carte, il écrit : « Encore des moments ensemble ! » Tout le monde répond : « Bonne année ! »", "Milo offre sa carte de vœux à ses amis."),
         ]),
    dict(id="carnaval-masque", titre="Le masque du carnaval", sousTitre="Chacun sa couleur",
         couleur="#a61e4d", age="3 à 6 ans", theme="carnaval", enfants=("renard", "chat"),
         resume="Au carnaval, Nina n'ose pas montrer son masque fait maison. Ses amis lui donnent le courage de rejoindre le défilé.",
         dedicace="Pour les artistes qui osent essayer.", pages=[
             ("masque", "Nina la renarde découpe un masque dans du carton. Elle y colle trois grandes plumes.", "Nina prépare un masque de carnaval à plumes."),
             ("ruban", "Dehors, les costumes brillent. « Mon masque est trop simple », murmure Nina.", "Nina hésite avec son masque et un ruban à la main."),
             ("masque", "Sam le chat montre son chapeau de papier tout froissé. « Moi aussi, je l'ai fait ! »", "Sam montre son chapeau en papier à Nina."),
             ("fanion", "Ils ajoutent un ruban bleu et un rond jaune au masque. Maintenant, il ressemble vraiment à Nina.", "Les amis décorent le masque avec des couleurs vives."),
             ("tambour", "Boum, boum ! Le tambour lance le défilé. Nina danse avec Sam et tous les voisins.", "Nina et Sam dansent au rythme d'un tambour."),
             ("masque", "Une plume tombe. Nina rit et la remet en place. Au carnaval, chacun invente sa fête !", "Nina porte son masque et rit parmi les fanions."),
         ]),
    dict(id="saint-valentin-cartes", titre="Des cartes pour les amis", sousTitre="La fête des petits mots",
         couleur="#e64980", age="3 à 6 ans", theme="saint-valentin", enfants=("souris", "ours"),
         resume="Pour la Saint-Valentin, Lou prépare des cartes. Elle découvre que quelques mots gentils peuvent toucher tout le monde.",
         dedicace="Pour toutes les personnes qu'on aime.", pages=[
             ("coeur", "C'est la Saint-Valentin. Lou la souris découpe des cœurs pour ses amis.", "Lou découpe des cœurs en papier rose."),
             ("carte", "Sur une carte, elle écrit : « Merci de jouer avec moi, Tim ! »", "Lou prépare une carte de remerciement."),
             ("ruban", "Sur une autre : « J'aime quand tu me racontes des histoires, Mamie ! »", "Lou attache un ruban à une carte pour Mamie."),
             ("carte", "Il reste une carte. Lou pense à Bibi, qui s'assoit souvent tout seul.", "Lou regarde une dernière carte encore blanche."),
             ("coeur", "Elle lui dessine un grand cœur et écrit : « Viens jouer avec nous ! » Bibi sourit jusqu'aux oreilles.", "Lou offre une carte à Bibi, qui sourit."),
             ("carte", "Bientôt, toute la bande échange des petits mots. Lou garde le sien tout près de son cœur.", "Les amis échangent leurs cartes autour de Lou."),
         ]),
    dict(id="musique-tambour", titre="Le tambour de la fête", sousTitre="La fête de la musique",
         couleur="#1971c2", age="3 à 6 ans", theme="musique", enfants=("lapin", "chat"),
         resume="À la fête de la musique, Sami pense ne savoir jouer de rien. Il découvre un rythme que tous peuvent suivre.",
         dedicace="Pour les musiciens de tous les jours.", pages=[
             ("note", "Dans la rue, c'est la fête de la musique ! Sami le lapin entend des notes partout.", "Sami écoute les notes de musique dans la rue."),
             ("tambour", "Léa joue du tambour : boum, boum ! Sami essaie, mais ses mains vont trop vite.", "Léa montre un tambour à Sami."),
             ("note", "Un oiseau chante. Sami l'imite : cui, cui ! Tout le monde s'arrête pour écouter.", "Sami écoute un oiseau qui chante."),
             ("tambour", "Sami tape doucement sur ses genoux : tap, tap. Léa reprend le même rythme.", "Sami et Léa inventent un rythme ensemble."),
             ("fanion", "Les voisins claquent des mains. La musique grandit dans toute la rue !", "Les voisins participent sous des fanions colorés."),
             ("note", "Sami rit : sa chanson est faite de voix, de mains et d'amis. Quelle belle fête !", "Sami et ses amis chantent ensemble."),
         ]),
    dict(id="mamans-bouquet", titre="Le bouquet de maman", sousTitre="Une surprise faite ensemble",
         couleur="#2b8a3e", age="3 à 6 ans", theme="fete-meres", enfants=("lapin", "souris"),
         resume="Pour la fête des mères, Zoé veut offrir un bouquet. La pluie change ses projets, mais lui donne une idée plus belle encore.",
         dedicace="Pour toutes les mamans et celles qui prennent soin de nous.", pages=[
             ("fleur", "Pour la fête des mères, Zoé la lapine veut cueillir trois jolies fleurs.", "Zoé regarde des fleurs dans le jardin."),
             ("nuage", "Mais ploc, ploc ! La pluie arrive. Les fleurs baissent la tête sous les gouttes.", "Un nuage de pluie arrose les fleurs du jardin."),
             ("pot", "Zoé trouve un petit pot vide. « On pourrait y planter quelque chose ! » dit son amie Mia.", "Zoé et Mia découvrent un pot de fleurs vide."),
             ("graine", "Elles mettent de la terre, une graine et un peu d'eau. Puis elles décorent le pot.", "Les amies plantent une graine dans un pot décoré."),
             ("carte", "Zoé ajoute une carte : « Nous la regarderons pousser ensemble. »", "Zoé écrit une carte pour accompagner le pot."),
             ("pot", "Maman serre Zoé dans ses bras. « Une surprise qui va grandir avec nous ! »", "Zoé offre le pot fleuri à sa maman."),
         ]),
    dict(id="papas-cerf-volant", titre="Le cerf-volant de papa", sousTitre="Une fête dans le vent",
         couleur="#0b7285", age="3 à 6 ans", theme="fete-peres", enfants=("renard", "ours"),
         resume="Pour la fête des pères, Léo fabrique un cerf-volant. Une réparation imprévue devient le meilleur moment de la journée.",
         dedicace="Pour tous les papas et ceux qui prennent soin de nous.", pages=[
             ("cerf-volant", "Pour la fête des pères, Léo le renard fabrique un cerf-volant rouge.", "Léo prépare un cerf-volant rouge avec son amie."),
             ("ruban", "Il attache une longue queue de rubans. « Papa va l'adorer ! »", "Léo ajoute des rubans colorés au cerf-volant."),
             ("nuage", "Au parc, le vent souffle fort. Le cerf-volant s'envole… puis sa queue se détache !", "Le vent emporte la queue du cerf-volant."),
             ("ruban", "Papa et Léo courent après les rubans. Ils les retrouvent dans un buisson.", "Papa et Léo retrouvent les rubans dans l'herbe."),
             ("cerf-volant", "Ensemble, ils font un gros nœud solide. Cette fois, le cerf-volant monte très haut.", "Papa aide Léo à réparer le cerf-volant."),
             ("cerf-volant", "« Le plus beau cadeau, dit Papa, c'est d'avoir joué avec toi ! » Léo lui prend la main.", "Papa et Léo regardent le cerf-volant voler."),
         ]),
    dict(id="anniversaire-gateau", titre="Le gâteau d'anniversaire", sousTitre="Une fête pour tout le monde",
         couleur="#e67700", age="3 à 6 ans", theme="anniversaire", enfants=("ours", "souris"),
         resume="Le jour de son anniversaire, Mina souhaite un grand gâteau. Elle découvre que ses amis en ont préparé un ensemble, chacun à sa façon.",
         dedicace="Pour les jours où l'on grandit d'un sourire.", pages=[
             ("ballon", "Aujourd'hui, c'est l'anniversaire de Mina l'oursonne ! Elle accroche un ballon à la porte.", "Mina décore sa porte avec un ballon."),
             ("table-vide", "Dans la cuisine, la table est vide. « Oh… il n'y a pas de gâteau ? »", "Mina regarde une table sans gâteau."),
             ("carte", "Son ami Tom arrive avec une carte. Puis Mia apporte des fraises, et Jo un grand bol.", "Les amis de Mina apportent une carte et de quoi cuisiner."),
             ("gateau", "Tous mélangent, versent et décorent. Un peu de farine vole même sur le nez de Tom !", "Les amis préparent ensemble un gâteau."),
             ("bougie", "Mina souffle les bougies. « J'avais demandé un gâteau… et j'ai eu tous mes amis ! »", "Mina souffle les bougies entourée de ses amis."),
             ("gateau", "Ils partagent chaque part. C'est le gâteau le plus joyeux du monde !", "Mina partage son gâteau d'anniversaire."),
         ]),
]
